# Tenserflow - Keras Example
https://www.tensorflow.org/tutorials/quickstart/beginner

### Import Packages & Modules

In [1]:
import tensorflow as tf

### Import Dataset

In [5]:
mnist = tf.keras.datasets.mnist

In [12]:
## Convert the samples from integers to floating-point numbers

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [16]:
x_train[[1]]

array([[[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ,
         0.

### Build Sequential Model

In [17]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [18]:
## Predict
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[-0.4058339 , -0.24972053, -0.08541173,  0.20276836, -0.5307249 ,
         0.18567486,  0.29962045,  0.72269785, -0.05406182,  0.52043426]],
      dtype=float32)

In [19]:
## Convert to probabilities
tf.nn.softmax(predictions).numpy()

array([[0.05835542, 0.06821508, 0.08039681, 0.10724914, 0.05150409,
        0.10543144, 0.1181561 , 0.1803833 , 0.08295716, 0.14735143]],
      dtype=float32)

In [20]:
## Return Loss Function 
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [23]:
loss_fn(y_train[:1], predictions).numpy()

2.2496943

In [24]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [25]:
model.fit(x_train, y_train, epochs=5)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 9s 156us/sample - loss: 0.2994 - accuracy: 0.9124
Epoch 2/5
60000/60000 [==============================] - 9s 148us/sample - loss: 0.1435 - accuracy: 0.9579
Epoch 3/5
60000/60000 [==============================] - 10s 160us/sample - loss: 0.1090 - accuracy: 0.9671
Epoch 4/5
60000/60000 [==============================] - 10s 172us/sample - loss: 0.0884 - accuracy: 0.9729
Epoch 5/5
60000/60000 [==============================] - 12s 192us/sample - loss: 0.0756 - accuracy: 0.9765


In [26]:
model.evaluate(x_test,  y_test, verbose=2)

10000/1 - 1s - loss: 0.0401 - accuracy: 0.9753


[0.07639185003752355, 0.9753]

In [27]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [29]:
probability_model(x_test[:5])

<tf.Tensor: id=30015, shape=(5, 10), dtype=float32, numpy=
array([[8.4996401e-08, 4.1277087e-08, 2.2217534e-06, 2.1372000e-03,
        2.3359648e-11, 2.4395997e-06, 3.6642499e-12, 9.9785078e-01,
        3.7786233e-06, 3.4638108e-06],
       [5.7759575e-08, 2.4690572e-04, 9.9958640e-01, 1.6352483e-04,
        4.3156383e-13, 4.9739565e-08, 2.6581962e-08, 1.6206913e-12,
        3.1211655e-06, 9.1471960e-12],
       [8.6036658e-07, 9.9926096e-01, 7.6262069e-05, 5.4411598e-06,
        2.2377259e-05, 1.1049280e-05, 5.5813518e-05, 4.1107886e-04,
        1.5362477e-04, 2.4478074e-06],
       [9.9981564e-01, 3.5142389e-08, 8.6161581e-06, 2.3706290e-05,
        8.3373277e-07, 2.4274626e-05, 3.7870446e-05, 6.1309969e-05,
        4.3244452e-07, 2.7303084e-05],
       [9.4293973e-06, 3.6051741e-08, 3.5849496e-06, 1.3989587e-08,
        9.9899036e-01, 7.4095517e-08, 7.5325329e-06, 2.5883272e-05,
        3.3943837e-07, 9.6281216e-04]], dtype=float32)>